version: "3"
services:
  web:
    build:
      context: .
    command: sh -c '(bundle check || bundle install) && thin start'
    volumes:
      - .:/app:cached
    #env_file: .env
    stdin_open: true
    tty: true
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "3000:3000"
    expose:
      - "3000"

  mongo:
    image: mongo:3.0
    ports:
      - "27017:27017"